### ISSUE TITLE
bug(windows): unexpected windows after each action

### ISSUE THREAD

**Issue by Kristinita** [swdotcom/swdc-sublime#2]
### 1. Summary

I get unexpected windows, where I wrote any symbol in Sublime Text. It makes it difficult to work.

### 2. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I register my account in **<https://app.software.com/>** → I install Software in Sublime Text via Package Control → I restart Sublime Text → I connected:

![Connect](https://i.imgur.com/WrTh9uS.png)

I wrote any text in any file type → I get actual behavior, not expected.

### 3. Expected behavior

Nothing prevents work in Sublime Text.

### 4. Actual behavior

![Actual](https://i.imgur.com/kAG7Yyt.gif)

After each key pressing I get some windows with path to Git in title bar:

![Git windows](https://i.imgur.com/c8B5A0f.png)

Sublime Text console output:

```text
Software.com: Requesting [GET: api.software.com/sessions?from=1546722000&summary=true]
C:\Users\SashaChernykh\.software\data.json file not found
Software.com: KPM incremented
Software.com: KPM incremented
Software.com: KPM incremented
Software.com: KPM incremented
Software.com: KPM incremented
Software.com: KPM incremented
Software.com: KPM incremented
Software.com: Requesting [GET: api.software.com/sessions?from=1546722000&summary=true]
```

### 5. Environment

+ Windows 10 Enterprise LTSB 64-bit EN
+ Sublime Text Version 3.1.1, Build 3176 Portable
+ git version 2.20.1.windows.1
+ Sublime Text Software 0.4.9

Thanks.

**Comment by andrewhli** [comment]
Hi Kristinita. Appreciate your thorough feedback. We're working to fix this issue and will let you know when it's done. In the meanwhile, we're curious about how you're using Software. Would you have a few minutes next week to talk about it?

**Comment by andrewhli** [comment]
Hi there. We've fixed this issue in v0.5.0 of the Software plugin for Sublime. Could you install v0.5.0 and let us know if everything looks good? https://packagecontrol.io/packages/Software

**Comment by Kristinita** [comment]
@andrewhli , I still get in console:

```
C:\Users\SashaChernykh\.software\data.json file not found
```

Possible, because I use portable Sublime Text. Thanks.

**Comment by andrewhli** [comment]
Thanks for bringing this up. I think it's a notification rather than an error, but we're looking into it and will hide the message going forward if it's not an error.

**Comment by andrewhli** [comment]
Hi there - The message about the data.json file not found is not an error (it is just a message), so the plugin will work as designed even if the data.json file is not found. Going forward, we will make this message less obtrusive.

**Comment by andrewhli** [comment]
Let me know if you see anything else. This has been very helpful.

**Comment by andrewhli** [comment]
Kristinita - We've pushed a fix that no longer shows the "data.json file not found" message as an error. Please check out v0.5.1: https://packagecontrol.io/packages/Software
